var app = {
    circles: true
}
app.path = [{
    letter: 'h',
    data: [{
        "data": "2:2",
        "x_data": 2,
        "y_data": 2
    }, {
        "data": "2:3",
        "x_data": 2,
        "y_data": 3
    }, {
        "data": "2:4",
        "x_data": 2,
        "y_data": 4
    }, {
        "data": "2:5",
        "x_data": 2,
        "y_data": 5
    }, {
        "data": "2:6",
        "x_data": 2,
        "y_data": 6
    }, {
        "data": "2:7",
        "x_data": 2,
        "y_data": 7
    }, {
        "data": "2:8",
        "x_data": 2,
        "y_data": 8
    }, {
        "data": "2:9",
        "x_data": 2,
        "y_data": 9
    }, {
        "data": "2:10",
        "x_data": 2,
        "y_data": 10
    }, {
        "data": "2:11",
        "x_data": 2,
        "y_data": 11
    }, {
        "data": "2:12",
        "x_data": 2,
        "y_data": 12
    }, {
        "data": "2:12",
        "x_data": 2,
        "y_data": 12
    }, {
        "data": "2:11",
        "x_data": 2,
        "y_data": 11
    }, {
        "data": "2:10",
        "x_data": 2,
        "y_data": 10
    }, {
        "data": "2:9",
        "x_data": 2,
        "y_data": 9
    }, {
        "data": "2:8",
        "x_data": 2,
        "y_data": 8
    }, {
        "data": "2:7",
        "x_data": 2,
        "y_data": 7
    }, {
        "data": "2:6",
        "x_data": 2,
        "y_data": 6
    }, {
        "data": "3:6",
        "x_data": 3,
        "y_data": 6
    }, {
        "data": "4:6",
        "x_data": 4,
        "y_data": 6
    }, {
        "data": "5:6",
        "x_data": 5,
        "y_data": 6
    }, {
        "data": "7:6",
        "x_data": 7,
        "y_data": 6
    }, {
        "data": "7:6",
        "x_data": 7,
        "y_data": 6
    }, {
        "data": "6:6",
        "x_data": 6,
        "y_data": 6
    }, {
        "data": "7:6",
        "x_data": 7,
        "y_data": 6
    }, {
        "data": "8:6",
        "x_data": 8,
        "y_data": 6
    }, {
        "data": "7:6",
        "x_data": 7,
        "y_data": 6
    }, {
        "data": "8:6",
        "x_data": 8,
        "y_data": 6
    }, {
        "data": "8:5",
        "x_data": 8,
        "y_data": 5
    }, {
        "data": "8:4",
        "x_data": 8,
        "y_data": 4
    }, {
        "data": "8:3",
        "x_data": 8,
        "y_data": 3
    }, {
        "data": "8:2",
        "x_data": 8,
        "y_data": 2
    }, {
        "data": "8:3",
        "x_data": 8,
        "y_data": 3
    }, {
        "data": "8:4",
        "x_data": 8,
        "y_data": 4
    }, {
        "data": "8:5",
        "x_data": 8,
        "y_data": 5
    }, {
        "data": "8:6",
        "x_data": 8,
        "y_data": 6
    }, {
        "data": "8:7",
        "x_data": 8,
        "y_data": 7
    }, {
        "data": "8:8",
        "x_data": 8,
        "y_data": 8
    }, {
        "data": "8:9",
        "x_data": 8,
        "y_data": 9
    }, {
        "data": "8:10",
        "x_data": 8,
        "y_data": 10
    }, {
        "data": "8:11",
        "x_data": 8,
        "y_data": 11
    }, {
        "data": "8:12",
        "x_data": 8,
        "y_data": 12
    }]
}, {
    letter: 'a',
    data: [{
        "data": "11:11",
        "x_data": 11,
        "y_data": 11
    }, {
        "data": "11:12",
        "x_data": 11,
        "y_data": 12
    }, {
        "data": "11:11",
        "x_data": 11,
        "y_data": 11
    }, {
        "data": "11:10",
        "x_data": 11,
        "y_data": 10
    }, {
        "data": "11:9",
        "x_data": 11,
        "y_data": 9
    }, {
        "data": "11:8",
        "x_data": 11,
        "y_data": 8
    }, {
        "data": "11:7",
        "x_data": 11,
        "y_data": 7
    }, {
        "data": "11:6",
        "x_data": 11,
        "y_data": 6
    }, {
        "data": "11:5",
        "x_data": 11,
        "y_data": 5
    }, {
        "data": "11:4",
        "x_data": 11,
        "y_data": 4
    }, {
        "data": "11:3",
        "x_data": 11,
        "y_data": 3
    }, {
        "data": "11:2",
        "x_data": 11,
        "y_data": 2
    }, {
        "data": "12:2",
        "x_data": 12,
        "y_data": 2
    }, {
        "data": "13:2",
        "x_data": 13,
        "y_data": 2
    }, {
        "data": "14:2",
        "x_data": 14,
        "y_data": 2
    }, {
        "data": "15:2",
        "x_data": 15,
        "y_data": 2
    }, {
        "data": "16:2",
        "x_data": 16,
        "y_data": 2
    }, {
        "data": "17:2",
        "x_data": 17,
        "y_data": 2
    }, {
        "data": "17:3",
        "x_data": 17,
        "y_data": 3
    }, {
        "data": "17:4",
        "x_data": 17,
        "y_data": 4
    }, {
        "data": "17:5",
        "x_data": 17,
        "y_data": 5
    }, {
        "data": "17:6",
        "x_data": 17,
        "y_data": 6
    }, {
        "data": "17:7",
        "x_data": 17,
        "y_data": 7
    }, {
        "data": "17:8",
        "x_data": 17,
        "y_data": 8
    }, {
        "data": "17:9",
        "x_data": 17,
        "y_data": 9
    }, {
        "data": "17:10",
        "x_data": 17,
        "y_data": 10
    }, {
        "data": "17:11",
        "x_data": 17,
        "y_data": 11
    }, {
        "data": "17:12",
        "x_data": 17,
        "y_data": 12
    }, {
        "data": "17:11",
        "x_data": 17,
        "y_data": 11
    }, {
        "data": "17:10",
        "x_data": 17,
        "y_data": 10
    }, {
        "data": "17:9",
        "x_data": 17,
        "y_data": 9
    }, {
        "data": "17:8",
        "x_data": 17,
        "y_data": 8
    }, {
        "data": "17:7",
        "x_data": 17,
        "y_data": 7
    }, {
        "data": "17:6",
        "x_data": 17,
        "y_data": 6
    }, {
        "data": "16:6",
        "x_data": 16,
        "y_data": 6
    }, {
        "data": "15:6",
        "x_data": 15,
        "y_data": 6
    }, {
        "data": "14:6",
        "x_data": 14,
        "y_data": 6
    }, {
        "data": "13:5",
        "x_data": 13,
        "y_data": 5
    }, {
        "data": "12:5",
        "x_data": 12,
        "y_data": 5
    }, {
        "data": "11:6",
        "x_data": 11,
        "y_data": 6
    }, {
        "data": "12:6",
        "x_data": 12,
        "y_data": 6
    }, {
        "data": "13:6",
        "x_data": 13,
        "y_data": 6
    }, {
        "data": "14:6",
        "x_data": 14,
        "y_data": 6
    }, {
        "data": "15:6",
        "x_data": 15,
        "y_data": 6
    }, {
        "data": "16:6",
        "x_data": 16,
        "y_data": 6
    }, {
        "data": "16:5",
        "x_data": 16,
        "y_data": 5
    }, {
        "data": "15:5",
        "x_data": 15,
        "y_data": 5
    }, {
        "data": "14:5",
        "x_data": 14,
        "y_data": 5
    }]
}, {
    letter: 'p',
    data: [{
        "data": "19:11",
        "x_data": 19,
        "y_data": 11
    }, {
        "data": "19:12",
        "x_data": 19,
        "y_data": 12
    }, {
        "data": "19:11",
        "x_data": 19,
        "y_data": 11
    }, {
        "data": "19:10",
        "x_data": 19,
        "y_data": 10
    }, {
        "data": "19:9",
        "x_data": 19,
        "y_data": 9
    }, {
        "data": "19:8",
        "x_data": 19,
        "y_data": 8
    }, {
        "data": "19:7",
        "x_data": 19,
        "y_data": 7
    }, {
        "data": "19:6",
        "x_data": 19,
        "y_data": 6
    }, {
        "data": "19:5",
        "x_data": 19,
        "y_data": 5
    }, {
        "data": "19:4",
        "x_data": 19,
        "y_data": 4
    }, {
        "data": "19:3",
        "x_data": 19,
        "y_data": 3
    }, {
        "data": "19:2",
        "x_data": 19,
        "y_data": 2
    }, {
        "data": "20:2",
        "x_data": 20,
        "y_data": 2
    }, {
        "data": "21:2",
        "x_data": 21,
        "y_data": 2
    }, {
        "data": "22:2",
        "x_data": 22,
        "y_data": 2
    }, {
        "data": "23:2",
        "x_data": 23,
        "y_data": 2
    }, {
        "data": "24:2",
        "x_data": 24,
        "y_data": 2
    }, {
        "data": "24:3",
        "x_data": 24,
        "y_data": 3
    }, {
        "data": "24:4",
        "x_data": 24,
        "y_data": 4
    }, {
        "data": "24:5",
        "x_data": 24,
        "y_data": 5
    }, {
        "data": "24:6",
        "x_data": 24,
        "y_data": 6
    }, {
        "data": "23:6",
        "x_data": 23,
        "y_data": 6
    }, {
        "data": "22:6",
        "x_data": 22,
        "y_data": 6
    }, {
        "data": "21:6",
        "x_data": 21,
        "y_data": 6
    }, {
        "data": "20:6",
        "x_data": 20,
        "y_data": 6
    }, {
        "data": "19:6",
        "x_data": 19,
        "y_data": 6
    }]
}, {
    letter: 'p2',
    data: [{
        "data": "26:11",
        "x_data": 26,
        "y_data": 11
    }, {
        "data": "26:12",
        "x_data": 26,
        "y_data": 12
    }, {
        "data": "26:11",
        "x_data": 26,
        "y_data": 11
    }, {
        "data": "26:10",
        "x_data": 26,
        "y_data": 10
    }, {
        "data": "26:9",
        "x_data": 26,
        "y_data": 9
    }, {
        "data": "26:8",
        "x_data": 26,
        "y_data": 8
    }, {
        "data": "26:7",
        "x_data": 26,
        "y_data": 7
    }, {
        "data": "26:6",
        "x_data": 26,
        "y_data": 6
    }, {
        "data": "26:5",
        "x_data": 26,
        "y_data": 5
    }, {
        "data": "26:4",
        "x_data": 26,
        "y_data": 4
    }, {
        "data": "26:3",
        "x_data": 26,
        "y_data": 3
    }, {
        "data": "26:2",
        "x_data": 26,
        "y_data": 2
    }, {
        "data": "27:2",
        "x_data": 27,
        "y_data": 2
    }, {
        "data": "28:2",
        "x_data": 28,
        "y_data": 2
    }, {
        "data": "29:2",
        "x_data": 29,
        "y_data": 2
    }, {
        "data": "30:2",
        "x_data": 30,
        "y_data": 2
    }, {
        "data": "30:3",
        "x_data": 30,
        "y_data": 3
    }, {
        "data": "30:4",
        "x_data": 30,
        "y_data": 4
    }, {
        "data": "30:5",
        "x_data": 30,
        "y_data": 5
    }, {
        "data": "30:6",
        "x_data": 30,
        "y_data": 6
    }, {
        "data": "29:6",
        "x_data": 29,
        "y_data": 6
    }, {
        "data": "28:6",
        "x_data": 28,
        "y_data": 6
    }, {
        "data": "27:6",
        "x_data": 27,
        "y_data": 6
    }, {
        "data": "26:6",
        "x_data": 26,
        "y_data": 6
    }]
}, {
    letter: 'y',
    data: [{
        "data": "32:3",
        "x_data": 32,
        "y_data": 3
    }, {
        "data": "32:4",
        "x_data": 32,
        "y_data": 4
    }, {
        "data": "32:5",
        "x_data": 32,
        "y_data": 5
    }, {
        "data": "32:6",
        "x_data": 32,
        "y_data": 6
    }, {
        "data": "33:6",
        "x_data": 33,
        "y_data": 6
    }, {
        "data": "34:6",
        "x_data": 34,
        "y_data": 6
    }, {
        "data": "35:6",
        "x_data": 35,
        "y_data": 6
    }, {
        "data": "36:7",
        "x_data": 36,
        "y_data": 7
    }, {
        "data": "37:7",
        "x_data": 37,
        "y_data": 7
    }, {
        "data": "37:6",
        "x_data": 37,
        "y_data": 6
    }, {
        "data": "37:5",
        "x_data": 37,
        "y_data": 5
    }, {
        "data": "37:4",
        "x_data": 37,
        "y_data": 4
    }, {
        "data": "37:3",
        "x_data": 37,
        "y_data": 3
    }, {
        "data": "37:4",
        "x_data": 37,
        "y_data": 4
    }, {
        "data": "37:5",
        "x_data": 37,
        "y_data": 5
    }, {
        "data": "37:6",
        "x_data": 37,
        "y_data": 6
    }, {
        "data": "37:7",
        "x_data": 37,
        "y_data": 7
    }, {
        "data": "36:8",
        "x_data": 36,
        "y_data": 8
    }, {
        "data": "36:9",
        "x_data": 36,
        "y_data": 9
    }, {
        "data": "36:10",
        "x_data": 36,
        "y_data": 10
    }, {
        "data": "36:11",
        "x_data": 36,
        "y_data": 11
    }, {
        "data": "36:12",
        "x_data": 36,
        "y_data": 12
    }, {
        "data": "36:13",
        "x_data": 36,
        "y_data": 13
    }, {
        "data": "35:13",
        "x_data": 35,
        "y_data": 13
    }, {
        "data": "34:13",
        "x_data": 34,
        "y_data": 13
    }, {
        "data": "33:13",
        "x_data": 33,
        "y_data": 13
    }, {
        "data": "32:13",
        "x_data": 32,
        "y_data": 13
    }, {
        "data": "32:12",
        "x_data": 32,
        "y_data": 12
    }, {
        "data": "32:11",
        "x_data": 32,
        "y_data": 11
    }, {
        "data": "32:10",
        "x_data": 32,
        "y_data": 10
    }, {
        "data": "33:10",
        "x_data": 33,
        "y_data": 10
    }, {
        "data": "33:9",
        "x_data": 33,
        "y_data": 9
    }, {
        "data": "34:9",
        "x_data": 34,
        "y_data": 9
    }, {
        "data": "34:10",
        "x_data": 34,
        "y_data": 10
    }]
}, {
    letter: 'B',
    data: [{
        "data": "8:16",
        "x_data": 8,
        "y_data": 16
    }, {
        "data": "8:17",
        "x_data": 8,
        "y_data": 17
    }, {
        "data": "8:18",
        "x_data": 8,
        "y_data": 18
    }, {
        "data": "8:19",
        "x_data": 8,
        "y_data": 19
    }, {
        "data": "8:20",
        "x_data": 8,
        "y_data": 20
    }, {
        "data": "8:21",
        "x_data": 8,
        "y_data": 21
    }, {
        "data": "8:22",
        "x_data": 8,
        "y_data": 22
    }, {
        "data": "8:23",
        "x_data": 8,
        "y_data": 23
    }, {
        "data": "8:24",
        "x_data": 8,
        "y_data": 24
    }, {
        "data": "8:25",
        "x_data": 8,
        "y_data": 25
    }, {
        "data": "7:26",
        "x_data": 7,
        "y_data": 26
    }, {
        "data": "7:27",
        "x_data": 7,
        "y_data": 27
    }, {
        "data": "7:28",
        "x_data": 7,
        "y_data": 28
    }, {
        "data": "8:29",
        "x_data": 8,
        "y_data": 29
    }, {
        "data": "8:28",
        "x_data": 8,
        "y_data": 28
    }, {
        "data": "8:27",
        "x_data": 8,
        "y_data": 27
    }, {
        "data": "8:26",
        "x_data": 8,
        "y_data": 26
    }, {
        "data": "8:25",
        "x_data": 8,
        "y_data": 25
    }, {
        "data": "8:24",
        "x_data": 8,
        "y_data": 24
    }, {
        "data": "8:23",
        "x_data": 8,
        "y_data": 23
    }, {
        "data": "8:22",
        "x_data": 8,
        "y_data": 22
    }, {
        "data": "7:21",
        "x_data": 7,
        "y_data": 21
    }, {
        "data": "7:20",
        "x_data": 7,
        "y_data": 20
    }, {
        "data": "7:19",
        "x_data": 7,
        "y_data": 19
    }, {
        "data": "7:18",
        "x_data": 7,
        "y_data": 18
    }, {
        "data": "7:17",
        "x_data": 7,
        "y_data": 17
    }, {
        "data": "7:16",
        "x_data": 7,
        "y_data": 16
    }, {
        "data": "7:17",
        "x_data": 7,
        "y_data": 17
    }, {
        "data": "7:18",
        "x_data": 7,
        "y_data": 18
    }, {
        "data": "7:19",
        "x_data": 7,
        "y_data": 19
    }, {
        "data": "7:20",
        "x_data": 7,
        "y_data": 20
    }, {
        "data": "7:21",
        "x_data": 7,
        "y_data": 21
    }, {
        "data": "7:22",
        "x_data": 7,
        "y_data": 22
    }, {
        "data": "7:23",
        "x_data": 7,
        "y_data": 23
    }, {
        "data": "7:24",
        "x_data": 7,
        "y_data": 24
    }, {
        "data": "7:25",
        "x_data": 7,
        "y_data": 25
    }, {
        "data": "7:26",
        "x_data": 7,
        "y_data": 26
    }, {
        "data": "7:27",
        "x_data": 7,
        "y_data": 27
    }, {
        "data": "7:28",
        "x_data": 7,
        "y_data": 28
    }, {
        "data": "7:29",
        "x_data": 7,
        "y_data": 29
    }, {
        "data": "8:29",
        "x_data": 8,
        "y_data": 29
    }, {
        "data": "9:29",
        "x_data": 9,
        "y_data": 29
    }, {
        "data": "10:29",
        "x_data": 10,
        "y_data": 29
    }, {
        "data": "11:29",
        "x_data": 11,
        "y_data": 29
    }, {
        "data": "12:29",
        "x_data": 12,
        "y_data": 29
    }, {
        "data": "13:29",
        "x_data": 13,
        "y_data": 29
    }, {
        "data": "13:28",
        "x_data": 13,
        "y_data": 28
    }, {
        "data": "13:27",
        "x_data": 13,
        "y_data": 27
    }, {
        "data": "13:26",
        "x_data": 13,
        "y_data": 26
    }, {
        "data": "14:26",
        "x_data": 14,
        "y_data": 26
    }, {
        "data": "14:25",
        "x_data": 14,
        "y_data": 25
    }, {
        "data": "15:25",
        "x_data": 15,
        "y_data": 25
    }, {
        "data": "15:24",
        "x_data": 15,
        "y_data": 24
    }, {
        "data": "15:23",
        "x_data": 15,
        "y_data": 23
    }, {
        "data": "14:22",
        "x_data": 14,
        "y_data": 22
    }, {
        "data": "13:22",
        "x_data": 13,
        "y_data": 22
    }, {
        "data": "12:21",
        "x_data": 12,
        "y_data": 21
    }, {
        "data": "11:21",
        "x_data": 11,
        "y_data": 21
    }, {
        "data": "10:21",
        "x_data": 10,
        "y_data": 21
    }, {
        "data": "9:21",
        "x_data": 9,
        "y_data": 21
    }, {
        "data": "8:21",
        "x_data": 8,
        "y_data": 21
    }, {
        "data": "9:21",
        "x_data": 9,
        "y_data": 21
    }, {
        "data": "10:21",
        "x_data": 10,
        "y_data": 21
    }, {
        "data": "11:21",
        "x_data": 11,
        "y_data": 21
    }, {
        "data": "12:21",
        "x_data": 12,
        "y_data": 21
    }, {
        "data": "13:21",
        "x_data": 13,
        "y_data": 21
    }, {
        "data": "14:21",
        "x_data": 14,
        "y_data": 21
    }, {
        "data": "15:21",
        "x_data": 15,
        "y_data": 21
    }, {
        "data": "16:21",
        "x_data": 16,
        "y_data": 21
    }, {
        "data": "16:20",
        "x_data": 16,
        "y_data": 20
    }, {
        "data": "16:19",
        "x_data": 16,
        "y_data": 19
    }, {
        "data": "16:18",
        "x_data": 16,
        "y_data": 18
    }, {
        "data": "16:17",
        "x_data": 16,
        "y_data": 17
    }, {
        "data": "16:16",
        "x_data": 16,
        "y_data": 16
    }, {
        "data": "16:15",
        "x_data": 16,
        "y_data": 15
    }, {
        "data": "9:15",
        "x_data": 9,
        "y_data": 15
    }, {
        "data": "8:15",
        "x_data": 8,
        "y_data": 15
    }, {
        "data": "7:15",
        "x_data": 7,
        "y_data": 15
    }, {
        "data": "8:15",
        "x_data": 8,
        "y_data": 15
    }, {
        "data": "9:15",
        "x_data": 9,
        "y_data": 15
    }, {
        "data": "10:15",
        "x_data": 10,
        "y_data": 15
    }, {
        "data": "11:15",
        "x_data": 11,
        "y_data": 15
    }, {
        "data": "12:15",
        "x_data": 12,
        "y_data": 15
    }, {
        "data": "13:15",
        "x_data": 13,
        "y_data": 15
    }, {
        "data": "14:15",
        "x_data": 14,
        "y_data": 15
    }, {
        "data": "15:15",
        "x_data": 15,
        "y_data": 15
    }, {
        "data": "16:15",
        "x_data": 16,
        "y_data": 15
    }]
}, {
    letter: 'D',
    data: [{
        "data": "24:16",
        "x_data": 24,
        "y_data": 16
    }, {
        "data": "24:17",
        "x_data": 24,
        "y_data": 17
    }, {
        "data": "24:18",
        "x_data": 24,
        "y_data": 18
    }, {
        "data": "24:19",
        "x_data": 24,
        "y_data": 19
    }, {
        "data": "24:20",
        "x_data": 24,
        "y_data": 20
    }, {
        "data": "24:21",
        "x_data": 24,
        "y_data": 21
    }, {
        "data": "24:22",
        "x_data": 24,
        "y_data": 22
    }, {
        "data": "24:23",
        "x_data": 24,
        "y_data": 23
    }, {
        "data": "24:24",
        "x_data": 24,
        "y_data": 24
    }, {
        "data": "24:25",
        "x_data": 24,
        "y_data": 25
    }, {
        "data": "24:26",
        "x_data": 24,
        "y_data": 26
    }, {
        "data": "24:27",
        "x_data": 24,
        "y_data": 27
    }, {
        "data": "24:28",
        "x_data": 24,
        "y_data": 28
    }, {
        "data": "24:29",
        "x_data": 24,
        "y_data": 29
    }, {
        "data": "25:29",
        "x_data": 25,
        "y_data": 29
    }, {
        "data": "25:28",
        "x_data": 25,
        "y_data": 28
    }, {
        "data": "26:28",
        "x_data": 26,
        "y_data": 28
    }, {
        "data": "27:28",
        "x_data": 27,
        "y_data": 28
    }, {
        "data": "27:29",
        "x_data": 27,
        "y_data": 29
    }, {
        "data": "28:29",
        "x_data": 28,
        "y_data": 29
    }, {
        "data": "29:29",
        "x_data": 29,
        "y_data": 29
    }, {
        "data": "30:29",
        "x_data": 30,
        "y_data": 29
    }, {
        "data": "31:29",
        "x_data": 31,
        "y_data": 29
    }, {
        "data": "31:28",
        "x_data": 31,
        "y_data": 28
    }, {
        "data": "30:28",
        "x_data": 30,
        "y_data": 28
    }, {
        "data": "30:28",
        "x_data": 30,
        "y_data": 28
    }, {
        "data": "31:28",
        "x_data": 31,
        "y_data": 28
    }, {
        "data": "32:28",
        "x_data": 32,
        "y_data": 28
    }, {
        "data": "32:27",
        "x_data": 32,
        "y_data": 27
    }, {
        "data": "32:26",
        "x_data": 32,
        "y_data": 26
    }, {
        "data": "33:26",
        "x_data": 33,
        "y_data": 26
    }, {
        "data": "33:25",
        "x_data": 33,
        "y_data": 25
    }, {
        "data": "33:24",
        "x_data": 33,
        "y_data": 24
    }, {
        "data": "33:23",
        "x_data": 33,
        "y_data": 23
    }, {
        "data": "33:22",
        "x_data": 33,
        "y_data": 22
    }, {
        "data": "33:21",
        "x_data": 33,
        "y_data": 21
    }, {
        "data": "33:20",
        "x_data": 33,
        "y_data": 20
    }, {
        "data": "32:20",
        "x_data": 32,
        "y_data": 20
    }, {
        "data": "32:19",
        "x_data": 32,
        "y_data": 19
    }, {
        "data": "32:18",
        "x_data": 32,
        "y_data": 18
    }, {
        "data": "31:18",
        "x_data": 31,
        "y_data": 18
    }, {
        "data": "31:17",
        "x_data": 31,
        "y_data": 17
    }, {
        "data": "30:17",
        "x_data": 30,
        "y_data": 17
    }, {
        "data": "29:17",
        "x_data": 29,
        "y_data": 17
    }, {
        "data": "28:17",
        "x_data": 28,
        "y_data": 17
    }, {
        "data": "27:17",
        "x_data": 27,
        "y_data": 17
    }, {
        "data": "27:16",
        "x_data": 27,
        "y_data": 16
    }, {
        "data": "26:16",
        "x_data": 26,
        "y_data": 16
    }, {
        "data": "25:16",
        "x_data": 25,
        "y_data": 16
    }, {
        "data": "24:16",
        "x_data": 24,
        "y_data": 16
    }, {
        "data": "25:16",
        "x_data": 25,
        "y_data": 16
    }, {
        "data": "25:17",
        "x_data": 25,
        "y_data": 17
    }, {
        "data": "25:18",
        "x_data": 25,
        "y_data": 18
    }, {
        "data": "25:19",
        "x_data": 25,
        "y_data": 19
    }, {
        "data": "25:20",
        "x_data": 25,
        "y_data": 20
    }, {
        "data": "25:21",
        "x_data": 25,
        "y_data": 21
    }, {
        "data": "25:22",
        "x_data": 25,
        "y_data": 22
    }, {
        "data": "25:23",
        "x_data": 25,
        "y_data": 23
    }, {
        "data": "25:24",
        "x_data": 25,
        "y_data": 24
    }, {
        "data": "25:25",
        "x_data": 25,
        "y_data": 25
    }, {
        "data": "24:26",
        "x_data": 24,
        "y_data": 26
    }, {
        "data": "24:27",
        "x_data": 24,
        "y_data": 27
    }, {
        "data": "24:28",
        "x_data": 24,
        "y_data": 28
    }, {
        "data": "25:28",
        "x_data": 25,
        "y_data": 28
    }, {
        "data": "26:28",
        "x_data": 26,
        "y_data": 28
    }, {
        "data": "27:28",
        "x_data": 27,
        "y_data": 28
    }, {
        "data": "26:28",
        "x_data": 26,
        "y_data": 28
    }, {
        "data": "25:28",
        "x_data": 25,
        "y_data": 28
    }, {
        "data": "26:28",
        "x_data": 26,
        "y_data": 28
    }, {
        "data": "27:28",
        "x_data": 27,
        "y_data": 28
    }, {
        "data": "28:28",
        "x_data": 28,
        "y_data": 28
    }, {
        "data": "29:28",
        "x_data": 29,
        "y_data": 28
    }, {
        "data": "30:28",
        "x_data": 30,
        "y_data": 28
    }]
}, {

    letter: 'A',
    data:

        [{
        "data": "13:37",
        "x_data": 13,
        "y_data": 37
    }, {
        "data": "13:36",
        "x_data": 13,
        "y_data": 36
    }, {
        "data": "13:35",
        "x_data": 13,
        "y_data": 35
    }, {
        "data": "13:34",
        "x_data": 13,
        "y_data": 34
    }, {
        "data": "13:33",
        "x_data": 13,
        "y_data": 33
    }, {
        "data": "14:32",
        "x_data": 14,
        "y_data": 32
    }, {
        "data": "15:32",
        "x_data": 15,
        "y_data": 32
    }, {
        "data": "16:32",
        "x_data": 16,
        "y_data": 32
    }, {
        "data": "17:32",
        "x_data": 17,
        "y_data": 32
    }, {
        "data": "18:32",
        "x_data": 18,
        "y_data": 32
    }, {
        "data": "18:33",
        "x_data": 18,
        "y_data": 33
    }, {
        "data": "18:34",
        "x_data": 18,
        "y_data": 34
    }, {
        "data": "18:35",
        "x_data": 18,
        "y_data": 35
    }, {
        "data": "18:36",
        "x_data": 18,
        "y_data": 36
    }, {
        "data": "18:37",
        "x_data": 18,
        "y_data": 37
    }, {
        "data": "18:38",
        "x_data": 18,
        "y_data": 38
    }, {
        "data": "18:37",
        "x_data": 18,
        "y_data": 37
    }, {
        "data": "18:36",
        "x_data": 18,
        "y_data": 36
    }, {
        "data": "18:35",
        "x_data": 18,
        "y_data": 35
    }, {
        "data": "17:34",
        "x_data": 17,
        "y_data": 34
    }, {
        "data": "16:34",
        "x_data": 16,
        "y_data": 34
    }, {
        "data": "15:34",
        "x_data": 15,
        "y_data": 34
    }, {
        "data": "14:34",
        "x_data": 14,
        "y_data": 34
    }, {
        "data": "13:34",
        "x_data": 13,
        "y_data": 34
    }, {
        "data": "13:35",
        "x_data": 13,
        "y_data": 35
    }, {
        "data": "13:36",
        "x_data": 13,
        "y_data": 36
    }, {
        "data": "13:37",
        "x_data": 13,
        "y_data": 37
    }, {
        "data": "13:38",
        "x_data": 13,
        "y_data": 38
    }, {
        "data": "13:37",
        "x_data": 13,
        "y_data": 37
    }, {
        "data": "13:36",
        "x_data": 13,
        "y_data": 36
    }, {
        "data": "13:35",
        "x_data": 13,
        "y_data": 35
    }, {
        "data": "13:34",
        "x_data": 13,
        "y_data": 34
    }, {
        "data": "13:33",
        "x_data": 13,
        "y_data": 33
    }, {
        "data": "13:32",
        "x_data": 13,
        "y_data": 32
    }]
}, {

    letter: 'G',
    data: [{
        "data": "7:10",
        "x_data": 7,
        "y_data": 10
    }, {
        "data": "8:10",
        "x_data": 8,
        "y_data": 10
    }, {
        "data": "9:10",
        "x_data": 9,
        "y_data": 10
    }, {
        "data": "10:10",
        "x_data": 10,
        "y_data": 10
    }, {
        "data": "11:10",
        "x_data": 11,
        "y_data": 10
    }, {
        "data": "12:10",
        "x_data": 12,
        "y_data": 10
    }, {
        "data": "13:10",
        "x_data": 13,
        "y_data": 10
    }, {
        "data": "13:11",
        "x_data": 13,
        "y_data": 11
    }, {
        "data": "13:12",
        "x_data": 13,
        "y_data": 12
    }, {
        "data": "13:13",
        "x_data": 13,
        "y_data": 13
    }, {
        "data": "13:14",
        "x_data": 13,
        "y_data": 14
    }, {
        "data": "13:15",
        "x_data": 13,
        "y_data": 15
    }, {
        "data": "12:15",
        "x_data": 12,
        "y_data": 15
    }, {
        "data": "11:16",
        "x_data": 11,
        "y_data": 16
    }, {
        "data": "10:16",
        "x_data": 10,
        "y_data": 16
    }, {
        "data": "9:16",
        "x_data": 9,
        "y_data": 16
    }, {
        "data": "8:16",
        "x_data": 8,
        "y_data": 16
    }, {
        "data": "7:16",
        "x_data": 7,
        "y_data": 16
    }, {
        "data": "6:16",
        "x_data": 6,
        "y_data": 16
    }, {
        "data": "5:16",
        "x_data": 5,
        "y_data": 16
    }, {
        "data": "5:15",
        "x_data": 5,
        "y_data": 15
    }, {
        "data": "4:14",
        "x_data": 4,
        "y_data": 14
    }, {
        "data": "4:13",
        "x_data": 4,
        "y_data": 13
    }, {
        "data": "4:12",
        "x_data": 4,
        "y_data": 12
    }, {
        "data": "4:11",
        "x_data": 4,
        "y_data": 11
    }, {
        "data": "4:10",
        "x_data": 4,
        "y_data": 10
    }, {
        "data": "4:9",
        "x_data": 4,
        "y_data": 9
    }, {
        "data": "4:8",
        "x_data": 4,
        "y_data": 8
    }, {
        "data": "4:7",
        "x_data": 4,
        "y_data": 7
    }, {
        "data": "4:6",
        "x_data": 4,
        "y_data": 6
    }, {
        "data": "4:5",
        "x_data": 4,
        "y_data": 5
    }, {
        "data": "5:5",
        "x_data": 5,
        "y_data": 5
    }, {
        "data": "5:4",
        "x_data": 5,
        "y_data": 4
    }, {
        "data": "6:4",
        "x_data": 6,
        "y_data": 4
    }, {
        "data": "7:4",
        "x_data": 7,
        "y_data": 4
    }, {
        "data": "8:4",
        "x_data": 8,
        "y_data": 4
    }, {
        "data": "9:4",
        "x_data": 9,
        "y_data": 4
    }, {
        "data": "10:4",
        "x_data": 10,
        "y_data": 4
    }, {
        "data": "11:4",
        "x_data": 11,
        "y_data": 4
    }, {
        "data": "12:4",
        "x_data": 12,
        "y_data": 4
    }, {
        "data": "13:4",
        "x_data": 13,
        "y_data": 4
    }, {
        "data": "14:4",
        "x_data": 14,
        "y_data": 4
    }, {
        "data": "14:5",
        "x_data": 14,
        "y_data": 5
    }, {
        "data": "14:6",
        "x_data": 14,
        "y_data": 6
    }, {
        "data": "13:6",
        "x_data": 13,
        "y_data": 6
    }, {
        "data": "12:6",
        "x_data": 12,
        "y_data": 6
    }, {
        "data": "12:5",
        "x_data": 12,
        "y_data": 5
    }, {
        "data": "13:5",
        "x_data": 13,
        "y_data": 5
    }, {
        "data": "13:5",
        "x_data": 13,
        "y_data": 5
    }]
}, {
    letter: 'i',
    data: [{
        "data": "22:11",
        "x_data": 22,
        "y_data": 11
    }, {
        "data": "22:12",
        "x_data": 22,
        "y_data": 12
    }, {
        "data": "22:13",
        "x_data": 22,
        "y_data": 13
    }, {
        "data": "22:14",
        "x_data": 22,
        "y_data": 14
    }, {
        "data": "22:15",
        "x_data": 22,
        "y_data": 15
    }, {
        "data": "22:16",
        "x_data": 22,
        "y_data": 16
    }, {
        "data": "22:17",
        "x_data": 22,
        "y_data": 17
    }, {
        "data": "22:18",
        "x_data": 22,
        "y_data": 18
    }, {
        "data": "22:19",
        "x_data": 22,
        "y_data": 19
    }, {
        "data": "22:20",
        "x_data": 22,
        "y_data": 20
    }, {
        "data": "22:21",
        "x_data": 22,
        "y_data": 21
    }, {
        "data": "22:22",
        "x_data": 22,
        "y_data": 22
    }, {
        "data": "22:23",
        "x_data": 22,
        "y_data": 23
    }, {
        "data": "23:23",
        "x_data": 23,
        "y_data": 23
    }, {
        "data": "24:23",
        "x_data": 24,
        "y_data": 23
    }, {
        "data": "25:23",
        "x_data": 25,
        "y_data": 23
    }, {
        "data": "25:22",
        "x_data": 25,
        "y_data": 22
    }, {
        "data": "25:21",
        "x_data": 25,
        "y_data": 21
    }, {
        "data": "24:21",
        "x_data": 24,
        "y_data": 21
    }, {
        "data": "23:21",
        "x_data": 23,
        "y_data": 21
    }, {
        "data": "22:21",
        "x_data": 22,
        "y_data": 21
    }, {
        "data": "23:22",
        "x_data": 23,
        "y_data": 22
    }, {
        "data": "24:22",
        "x_data": 24,
        "y_data": 22
    }, {
        "data": "21:7",
        "x_data": 21,
        "y_data": 7
    }, {
        "data": "21:8",
        "x_data": 21,
        "y_data": 8
    }, {
        "data": "22:8",
        "x_data": 22,
        "y_data": 8
    }, {
        "data": "23:8",
        "x_data": 23,
        "y_data": 8
    }, {
        "data": "23:7",
        "x_data": 23,
        "y_data": 7
    }, {
        "data": "22:7",
        "x_data": 22,
        "y_data": 7
    }, {
        "data": "22:6",
        "x_data": 22,
        "y_data": 6
    }, {
        "data": "23:6",
        "x_data": 23,
        "y_data": 6
    }, {
        "data": "22:6",
        "x_data": 22,
        "y_data": 6
    }, {
        "data": "21:6",
        "x_data": 21,
        "y_data": 6
    }]
}, {
    letter: 'O',
    data: [{
        "data": "30:16",
        "x_data": 30,
        "y_data": 16
    }, {
        "data": "31:16",
        "x_data": 31,
        "y_data": 16
    }, {
        "data": "32:16",
        "x_data": 32,
        "y_data": 16
    }, {
        "data": "33:16",
        "x_data": 33,
        "y_data": 16
    }, {
        "data": "34:16",
        "x_data": 34,
        "y_data": 16
    }, {
        "data": "35:16",
        "x_data": 35,
        "y_data": 16
    }, {
        "data": "36:16",
        "x_data": 36,
        "y_data": 16
    }, {
        "data": "37:16",
        "x_data": 37,
        "y_data": 16
    }, {
        "data": "37:17",
        "x_data": 37,
        "y_data": 17
    }, {
        "data": "37:18",
        "x_data": 37,
        "y_data": 18
    }, {
        "data": "37:19",
        "x_data": 37,
        "y_data": 19
    }, {
        "data": "37:20",
        "x_data": 37,
        "y_data": 20
    }, {
        "data": "37:21",
        "x_data": 37,
        "y_data": 21
    }, {
        "data": "37:22",
        "x_data": 37,
        "y_data": 22
    }, {
        "data": "36:23",
        "x_data": 36,
        "y_data": 23
    }, {
        "data": "36:24",
        "x_data": 36,
        "y_data": 24
    }, {
        "data": "36:25",
        "x_data": 36,
        "y_data": 25
    }, {
        "data": "36:26",
        "x_data": 36,
        "y_data": 26
    }, {
        "data": "36:27",
        "x_data": 36,
        "y_data": 27
    }, {
        "data": "35:27",
        "x_data": 35,
        "y_data": 27
    }, {
        "data": "34:27",
        "x_data": 34,
        "y_data": 27
    }, {
        "data": "33:27",
        "x_data": 33,
        "y_data": 27
    }, {
        "data": "32:27",
        "x_data": 32,
        "y_data": 27
    }, {
        "data": "31:27",
        "x_data": 31,
        "y_data": 27
    }, {
        "data": "30:27",
        "x_data": 30,
        "y_data": 27
    }, {
        "data": "29:27",
        "x_data": 29,
        "y_data": 27
    }, {
        "data": "29:26",
        "x_data": 29,
        "y_data": 26
    }, {
        "data": "29:25",
        "x_data": 29,
        "y_data": 25
    }, {
        "data": "29:24",
        "x_data": 29,
        "y_data": 24
    }, {
        "data": "29:23",
        "x_data": 29,
        "y_data": 23
    }, {
        "data": "29:22",
        "x_data": 29,
        "y_data": 22
    }, {
        "data": "29:21",
        "x_data": 29,
        "y_data": 21
    }, {
        "data": "29:20",
        "x_data": 29,
        "y_data": 20
    }, {
        "data": "28:20",
        "x_data": 28,
        "y_data": 20
    }, {
        "data": "28:19",
        "x_data": 28,
        "y_data": 19
    }, {
        "data": "28:18",
        "x_data": 28,
        "y_data": 18
    }, {
        "data": "28:17",
        "x_data": 28,
        "y_data": 17
    }, {
        "data": "29:17",
        "x_data": 29,
        "y_data": 17
    }, {
        "data": "29:16",
        "x_data": 29,
        "y_data": 16
    }, {
        "data": "30:16",
        "x_data": 30,
        "y_data": 16
    }, {
        "data": "31:16",
        "x_data": 31,
        "y_data": 16
    }, {
        "data": "32:16",
        "x_data": 32,
        "y_data": 16
    }, {
        "data": "33:16",
        "x_data": 33,
        "y_data": 16
    }, {
        "data": "34:16",
        "x_data": 34,
        "y_data": 16
    }, {
        "data": "35:16",
        "x_data": 35,
        "y_data": 16
    }, {
        "data": "36:16",
        "x_data": 36,
        "y_data": 16
    }, {
        "data": "36:17",
        "x_data": 36,
        "y_data": 17
    }, {
        "data": "37:17",
        "x_data": 37,
        "y_data": 17
    }, {
        "data": "37:18",
        "x_data": 37,
        "y_data": 18
    }, {
        "data": "37:19",
        "x_data": 37,
        "y_data": 19
    }, {
        "data": "37:20",
        "x_data": 37,
        "y_data": 20
    }, {
        "data": "37:21",
        "x_data": 37,
        "y_data": 21
    }, {
        "data": "36:22",
        "x_data": 36,
        "y_data": 22
    }, {
        "data": "36:23",
        "x_data": 36,
        "y_data": 23
    }, {
        "data": "36:24",
        "x_data": 36,
        "y_data": 24
    }, {
        "data": "37:24",
        "x_data": 37,
        "y_data": 24
    }, {
        "data": "37:23",
        "x_data": 37,
        "y_data": 23
    }, {
        "data": "37:22",
        "x_data": 37,
        "y_data": 22
    }, {
        "data": "37:23",
        "x_data": 37,
        "y_data": 23
    }, {
        "data": "37:24",
        "x_data": 37,
        "y_data": 24
    }, {
        "data": "37:25",
        "x_data": 37,
        "y_data": 25
    }, {
        "data": "37:26",
        "x_data": 37,
        "y_data": 26
    }, {
        "data": "37:27",
        "x_data": 37,
        "y_data": 27
    }, {
        "data": "37:26",
        "x_data": 37,
        "y_data": 26
    }, {
        "data": "37:25",
        "x_data": 37,
        "y_data": 25
    }, {
        "data": "36:24",
        "x_data": 36,
        "y_data": 24
    }, {
        "data": "36:23",
        "x_data": 36,
        "y_data": 23
    }, {
        "data": "36:22",
        "x_data": 36,
        "y_data": 22
    }, {
        "data": "36:21",
        "x_data": 36,
        "y_data": 21
    }, {
        "data": "36:20",
        "x_data": 36,
        "y_data": 20
    }, {
        "data": "36:19",
        "x_data": 36,
        "y_data": 19
    }, {
        "data": "36:18",
        "x_data": 36,
        "y_data": 18
    }, {
        "data": "36:17",
        "x_data": 36,
        "y_data": 17
    }, {
        "data": "35:16",
        "x_data": 35,
        "y_data": 16
    }, {
        "data": "34:16",
        "x_data": 34,
        "y_data": 16
    }, {
        "data": "33:16",
        "x_data": 33,
        "y_data": 16
    }, {
        "data": "32:16",
        "x_data": 32,
        "y_data": 16
    }, {
        "data": "31:16",
        "x_data": 31,
        "y_data": 16
    }, {
        "data": "30:16",
        "x_data": 30,
        "y_data": 16
    }, {
        "data": "29:15",
        "x_data": 29,
        "y_data": 15
    }, {
        "data": "28:15",
        "x_data": 28,
        "y_data": 15
    }, {
        "data": "28:16",
        "x_data": 28,
        "y_data": 16
    }, {
        "data": "28:17",
        "x_data": 28,
        "y_data": 17
    }, {
        "data": "28:18",
        "x_data": 28,
        "y_data": 18
    }, {
        "data": "28:19",
        "x_data": 28,
        "y_data": 19
    }, {
        "data": "28:20",
        "x_data": 28,
        "y_data": 20
    }, {
        "data": "28:21",
        "x_data": 28,
        "y_data": 21
    }, {
        "data": "28:22",
        "x_data": 28,
        "y_data": 22
    }, {
        "data": "28:23",
        "x_data": 28,
        "y_data": 23
    }, {
        "data": "28:24",
        "x_data": 28,
        "y_data": 24
    }, {
        "data": "28:25",
        "x_data": 28,
        "y_data": 25
    }, {
        "data": "28:26",
        "x_data": 28,
        "y_data": 26
    }, {
        "data": "28:27",
        "x_data": 28,
        "y_data": 27
    }, {
        "data": "28:26",
        "x_data": 28,
        "y_data": 26
    }, {
        "data": "28:25",
        "x_data": 28,
        "y_data": 25
    }, {
        "data": "29:24",
        "x_data": 29,
        "y_data": 24
    }, {
        "data": "29:23",
        "x_data": 29,
        "y_data": 23
    }, {
        "data": "29:22",
        "x_data": 29,
        "y_data": 22
    }, {
        "data": "29:21",
        "x_data": 29,
        "y_data": 21
    }, {
        "data": "29:20",
        "x_data": 29,
        "y_data": 20
    }, {
        "data": "29:19",
        "x_data": 29,
        "y_data": 19
    }, {
        "data": "29:18",
        "x_data": 29,
        "y_data": 18
    }, {
        "data": "29:17",
        "x_data": 29,
        "y_data": 17
    }, {
        "data": "29:16",
        "x_data": 29,
        "y_data": 16
    }, {
        "data": "29:15",
        "x_data": 29,
        "y_data": 15
    }, {
        "data": "30:15",
        "x_data": 30,
        "y_data": 15
    }, {
        "data": "31:15",
        "x_data": 31,
        "y_data": 15
    }, {
        "data": "32:15",
        "x_data": 32,
        "y_data": 15
    }, {
        "data": "33:15",
        "x_data": 33,
        "y_data": 15
    }, {
        "data": "34:15",
        "x_data": 34,
        "y_data": 15
    }, {
        "data": "35:15",
        "x_data": 35,
        "y_data": 15
    }, {
        "data": "36:15",
        "x_data": 36,
        "y_data": 15
    }, {
        "data": "37:15",
        "x_data": 37,
        "y_data": 15
    }, {
        "data": "37:16",
        "x_data": 37,
        "y_data": 16
    }, {
        "data": "37:17",
        "x_data": 37,
        "y_data": 17
    }, {
        "data": "37:18",
        "x_data": 37,
        "y_data": 18
    }, {
        "data": "37:19",
        "x_data": 37,
        "y_data": 19
    }, {
        "data": "37:20",
        "x_data": 37,
        "y_data": 20
    }, {
        "data": "37:21",
        "x_data": 37,
        "y_data": 21
    }, {
        "data": "37:22",
        "x_data": 37,
        "y_data": 22
    }, {
        "data": "37:23",
        "x_data": 37,
        "y_data": 23
    }, {
        "data": "37:24",
        "x_data": 37,
        "y_data": 24
    }, {
        "data": "37:25",
        "x_data": 37,
        "y_data": 25
    }, {
        "data": "36:26",
        "x_data": 36,
        "y_data": 26
    }, {
        "data": "35:26",
        "x_data": 35,
        "y_data": 26
    }, {
        "data": "34:26",
        "x_data": 34,
        "y_data": 26
    }, {
        "data": "33:26",
        "x_data": 33,
        "y_data": 26
    }, {
        "data": "32:26",
        "x_data": 32,
        "y_data": 26
    }, {
        "data": "31:26",
        "x_data": 31,
        "y_data": 26
    }, {
        "data": "30:26",
        "x_data": 30,
        "y_data": 26
    }, {
        "data": "29:26",
        "x_data": 29,
        "y_data": 26
    }]
}]